### PR TITLE
Add TEST README.md fixes #344

### LINKED ISSUE #344: ContribFest: Link to test docs is broken in DEVELOPMENT.md file
The link to the test docs from the DEVELOPMENT.md file points to `./test/README.md` which does not exists.

Should we use the one from https://github.com/knative/eventing (core) here?

@lionelvillard @aslom @psschwei

### PR DESCRIPTION
**Pull request by avinashdesireddy**
Add readme file in test directory with instructions to run tests
Fixes #344 

Signed-off-by: Avinash Desireddy <avinashr.desireddy@gmail.com>

### CODE REVIEW

**Comment by avinashdesireddy** [comment]
@psschwei I think I addressed the issue, please review and run the tests.

another question- Can I trigger the tests or it can be done only by maintainers?

**Comment by psschwei** [comment]
> another question- Can I trigger the tests or it can be done only by maintainers?

You need to be a member of the knative orgs to have tests run automatically

**Comment by psschwei** [comment]
these two failures are unrelated to your PR...

**Comment by psschwei** [comment]
#349 should fix the test errors

**Comment by avinashdesireddy** [comment]
> > another question- Can I trigger the tests or it can be done only by maintainers?
> 
> You need to be a member of the knative orgs to have tests run automatically

@psschwei Got it. Thanks!!

Looking at the other failures, none of them seem to be related to the changes I made. Is it okay to merge this or do I need to add any additional details here?

**Comment by psschwei** [comment]
let's let #349 merge first and then we can retest/merge this one

**Review by sss-ng — APPROVED** [review]

**Comment by avinashdesireddy** [comment]
> let's let #349 merge first and then we can retest/merge this one

Looks like #349 is merged, can we retest and merge this?

**Review by psschwei — COMMENTED** [review]
/lgtm
/approve

Thanks for persisting with this!

**Pull request merged**
